export const TOGGLE_RIGHT_DRAWER = 'TOGGLE_RIGHT_DRAWER';
export const SET_BEFORE_INSTALL_PROMPT_FIRE = 'SET_BEFORE_INSTALL_PROMPT_FIRE';
export const HIDE_ONBOARDING_JOURNEY = 'HIDE_ONBOARDING_JOURNEY';
